postgres__packages:
  - postgresql #устанавливаем PostgreSQL
  - python3-psycopg2 #устанавливаем библиотеку для работы с PostgreSQL из Python  
  - acl #устанавливаем утилиту для управления списком контроля доступа (Access Control List, ACL)

postgres__data_dir: /data/postgres/data # путь для данных PostgreSQL

postgres__opts:
  port: 5432
  max_connections: 100

postgres__hba_rules: #разрешаем локальный вход под пользователем postgres
  - type: local
    database: all
    user: postgres
    method: peer